# Generated by Django 5.2 on 2025-05-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image_url',
            field=models.URLField(blank=True, default='https://th.bing.com/th/id/R.c33768fe42791b045951429e0502701a?rik=Os5%2fNGBq8DeSgw&riu=http%3a%2f%2fwww.pixelstalk.net%2fwp-content%2fuploads%2f2016%2f06%2fCar-desktop-backgrounds-car-wallpapers-car-hd-photo.jpg&ehk=QhMJa%2bXR7ppHcBMx0gOMEXaZCCSYCneetAeXVsfTaPc%3d&risl=&pid=ImgRaw&r=0', max_length=500, null=True),
        ),
    ]
