# Generated by Django 5.2 on 2025-05-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0002_car_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='registration_number',
        ),
        migrations.AddField(
            model_name='car',
            name='transmission_type',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATIC', 'Automatic')], default='AUTOMATIC', max_length=20),
        ),
    ]
